# Generated by Django 4.2.29 on 2026-04-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
