# Generated by Django migrations
import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guests", to="events.event")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("table_number", models.CharField(max_length=50)),
                ("unique_token", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("qr_code_image", models.ImageField(blank=True, null=True, upload_to="qr_codes/")),
                ("has_checked_in", models.BooleanField(default=False)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("event", "email")},
            },
        ),
    ]
