# Generated by Django migrations
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="rsvp_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("attending", "Attending"), ("declined", "Declined")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="rsvp_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="is_placeholder",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="guest",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                fields=("event", "email"),
                name="unique_event_email",
                condition=Q(email__isnull=False) & ~Q(email=""),
            ),
        ),
    ]
