# Generated by Django migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0002_guest_rsvp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="table_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
