# Generated by Django migrations
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checkin_logs", to="guests.guest")),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("scanned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="checkin_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
    ]
